Controllers/GeneralController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreCatalog.Data;
using StoreCatalog.Models;

namespace StoreCatalog.Controllers
{
    public class GeneralController : Controller
    {
        private readonly ApplicationDbContext _db;

        public GeneralController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult IndexGeneral()
        {
            var processors = _db.processors.ToList();
            var motherboards = _db.motherboards.ToList();
            var graphicsCards = _db.graphicscards.ToList();

            CatalogueItem catalogue = new CatalogueItem()
            {
                Processors = processors,
                Motherboards = motherboards,
                GraphicsCards = graphicsCards

            };
            return View(catalogue);
        }

        //Handling Processors creating process
        public IActionResult CreateProcessor()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateProcessor(Processor obj)
        {
            
            if (ModelState.IsValid)
            {
                _db.processors.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Item created successfully !";
                return RedirectToAction("IndexGeneral");

            }
            return View(obj);
        }

		//Handling Processors Editing process
		public IActionResult EditProcessor(int? id )
		{
            if (id == null || id == 0)
            { 
                return NotFound();
            }

            var processorFromDb = _db.processors.Find(id);

            if (processorFromDb == null)
            {
                return NotFound();
            }
			return View(processorFromDb);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult EditProcessor(Processor obj)
		{

			if (ModelState.IsValid)
			{
				_db.processors.Update(obj);
                TempData["success"] = "Item updated successfully !";
                _db.SaveChanges();
				return RedirectToAction("IndexGeneral");

			}
			return View(obj);
		}

        //Handling Processors Deleting 
        public IActionResult DeleteProcessor(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var processorFromDb = _db.processors.Find(id);

            if (processorFromDb == null)
            {
                return NotFound();
            }
            return View(processorFromDb);
        }

        [HttpPost("DeleteProcessorPOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteProcessorPOST(int? id)
        {

            var obj = _db.processors.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.processors.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Item deleted successfully !";
            return RedirectToAction("IndexGeneral");

        }
        //---------------------------------------------------------------------

        //Handling Motherboards creating process
        public IActionResult CreateMotherboards()
            {
            return View();
            }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateMotherboards(Motherboard obj)
        {
            
            if (ModelState.IsValid)
            {
                _db.motherboards.Add(obj);
                TempData["success"] = "Item created successfully !";
                _db.SaveChanges();
                return RedirectToAction("IndexGeneral");
            }
            return View(obj);
        }

		//Handling Motherboard Editing process
		public IActionResult EditMotherboard(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var motherboardFromDb = _db.motherboards.Find(id);

			if (motherboardFromDb == null)
			{
				return NotFound();
			}
			return View(motherboardFromDb);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult EditMotherboard(Motherboard obj)
		{

			if (ModelState.IsValid)
			{
				_db.motherboards.Update(obj);
				_db.SaveChanges();
                TempData["success"] = "Item updated successfully !";
                return RedirectToAction("IndexGeneral");

			}
			return View(obj);
		}

        //Handling Motherboard Deleting 
        public IActionResult DeleteMotherboard(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var motherboardFromDb = _db.motherboards.Find(id);

            if (motherboardFromDb == null)
            {
                return NotFound();
            }
            return View(motherboardFromDb);
        }

        [HttpPost("DeleteMotherboardPOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMotherboardPOST(int? id)
        {

            var obj = _db.motherboards.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.motherboards.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Item deleted successfully !";
            return RedirectToAction("IndexGeneral");

        }
        //---------------------------------------------------------------------

        //Handling GraphicsCards creating process
        public IActionResult CreateGraphicsCards()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateGraphicsCards(GraphicsCard obj)
        {   
            
            if (ModelState.IsValid)
            {
                _db.graphicscards.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Item created successfully !";
                return RedirectToAction("IndexGeneral");
            }
            return View(obj);

        }

		//Handling GraphicsCard Editing process
		public IActionResult EditGraphicsCard(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var graphicsCardFromDb = _db.graphicscards.Find(id);

			if (graphicsCardFromDb == null)
			{
				return NotFound();
			}
			return View(graphicsCardFromDb);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult EditGraphicsCard(GraphicsCard obj)
		{

			if (ModelState.IsValid)
			{
				_db.graphicscards.Update(obj);
				_db.SaveChanges();
                TempData["success"] = "Item updated successfully !";
                return RedirectToAction("IndexGeneral");

			}
			return View(obj);
		}

        //Handling GraphicsCard Deleting 
        public IActionResult DeleteGraphicsCard(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var graphicsCardFromDb = _db.graphicscards.Find(id);

            if (graphicsCardFromDb == null)
            {
                return NotFound();
            }
            return View(graphicsCardFromDb);
        }

        [HttpPost("DeleteGraphicsCardPOST")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteGraphicsCardPOST(int? id)
        {

            var obj = _db.graphicscards.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.graphicscards.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Item deleted successfully !";
            return RedirectToAction("IndexGeneral");

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreCatalog</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreCatalog.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                <span class="visually-hidden">(current)</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="General" asp-action="IndexGeneral">Catalogue</a>
                        </li>
                      @*  <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    @*<form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-secondary">
        <div class="container">
            &copy; 2023 - StoreCatalogue - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}